# Generated by Django 4.2.6 on 2023-11-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='month',
            field=models.CharField(choices=[('BACKGROUND', 'background'), ('LOGO', 'logo'), ('GAME', 'game'), ('VFX', 'vfx')], default='BACKGROUND', max_length=10),
        ),
    ]
